route:
  group_by: ['Alertname']
  receiver: gmail
receivers:
- name: 'gmail'
  email_configs:
  - to: 'toantd1202@gmail.com'
    from: 'toantd1202@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: "toantd1202@gmail.com"
    auth_identity: "toantd1202@gmail.com"
    auth_password: "PASSWORD"
