global:
  scrape_interval: 30s
scrape_configs:
- job_name: 'node'
  static_configs:
  - targets: ['localhost:9090']
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['am1:9093','am2:9094']
rule_files:
  - rulefile.yml
